# Generated by Django 6.0.1 on 2026-01-08 16:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('facilities', models.CharField(help_text='e.g., AC, Sound System, WiFi', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='halls/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('coordinator_name', models.CharField(max_length=100, verbose_name='Program Head / Coordinator')),
                ('coordinator_mobile', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('stage_size', models.CharField(blank=True, choices=[('Large', 'Large'), ('Small', 'Small')], max_length=10)),
                ('audience_count', models.PositiveIntegerField(default=0)),
                ('chair_type', models.CharField(blank=True, choices=[('Wheel', 'Wheel'), ('Fiber', 'Fiber')], max_length=10)),
                ('chair_count', models.PositiveIntegerField(default=0)),
                ('mic_count', models.PositiveIntegerField(default=0)),
                ('speaker_count', models.PositiveIntegerField(default=0)),
                ('projector_count', models.PositiveIntegerField(default=0)),
                ('laptop_count', models.PositiveIntegerField(default=0)),
                ('req_agarbatti', models.BooleanField(default=False, verbose_name='Incense Sticks (Agarbatti)')),
                ('req_matchbox', models.BooleanField(default=False, verbose_name='Matchbox')),
                ('req_oil', models.BooleanField(default=False, verbose_name='Oil')),
                ('req_wati', models.BooleanField(default=False, verbose_name='Cotton Wicks (Wati)')),
                ('req_kapur', models.BooleanField(default=False, verbose_name='Camphor (Kapur)')),
                ('req_satarangi', models.CharField(blank=True, max_length=100, verbose_name='Satarangi/Mat')),
                ('req_carpet', models.BooleanField(default=False, verbose_name='Red Carpet')),
                ('req_mandap', models.BooleanField(default=False, verbose_name='Mandap')),
                ('req_saraswati_photo', models.BooleanField(default=False, verbose_name='Saraswati Photo')),
                ('req_samai', models.BooleanField(default=False, verbose_name='Traditional Lamp (Samai)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hallapp.hall')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
