# Generated by Django 6.0.1 on 2026-01-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='image',
        ),
    ]
