# Generated by Django 6.0.1 on 2026-01-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0003_booking_approved_at_booking_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
