# Generated by Django 6.0 on 2026-01-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0004_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
