# Generated by Django 6.0.1 on 2026-01-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0005_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
