# Generated by Django 6.0.1 on 2026-01-13 03:35

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_default_admins(apps, schema_editor):
    """
    Create default admin users in the database
    """
    User = apps.get_model('hallapp', 'User')
    Admin = apps.get_model('hallapp', 'Admin')
    
    default_admins = [
        {
            'username': 'harshadwaman4@gmail.com',
            'email': 'harshadwaman4@gmail.com',
            'password': '9011818144',
            'first_name': 'Harshad',
            'last_name': 'Waman',
            'admin_code': 'ADMIN001'
        },
        {
            'username': 'nayanpatilnp11@gmail.com',
            'email': 'nayanpatilnp11@gmail.com', 
            'password': 'nayan2105',
            'first_name': 'Nayan',
            'last_name': 'Patil',
            'admin_code': 'ADMIN002'
        }
    ]
    
    for admin_data in default_admins:
        # Check if user exists, if not create it
        user, created = User.objects.get_or_create(
            username=admin_data['username'],
            defaults={
                'email': admin_data['email'],
                'first_name': admin_data['first_name'],
                'last_name': admin_data['last_name'],
                'user_type': 'admin',
                'is_staff': True,
                'is_superuser': True,
                'is_active': True
            }
        )
        
        # If user was created, set password
        if created:
            user.set_password(admin_data['password'])
            user.save()
        else:
            # Update existing user to be admin
            user.user_type = 'admin'
            user.is_staff = True
            user.is_superuser = True
            user.first_name = admin_data['first_name']
            user.last_name = admin_data['last_name']
            user.save()
        
        # Create or update admin profile
        admin_profile, created = Admin.objects.get_or_create(
            user=user,
            defaults={
                'admin_code': admin_data['admin_code'],
                'department': 'Administration'
            }
        )


def reverse_create_default_admins(apps, schema_editor):
    """
    Reverse the migration - delete default admin users
    """
    User = apps.get_model('hallapp', 'User')
    Admin = apps.get_model('hallapp', 'Admin')
    
    admin_codes = ['ADMIN001', 'ADMIN002']
    Admin.objects.filter(admin_code__in=admin_codes).delete()
    User.objects.filter(username__in=['harshadwaman4@gmail.com', 'nayanpatilnp11@gmail.com']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0005_add_user_type_and_admin_model'),
    ]

    operations = [
        migrations.RunPython(create_default_admins, reverse_create_default_admins),
    ]
