# Generated by Django 6.0 on 2026-01-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0005_user_user_type'),
        ('hallapp', '0006_create_default_admins'),
    ]

    operations = [
    ]
