# Generated by Django 6.0.1 on 2026-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0006_remove_hall_is_active_hall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10),
        ),
    ]
