# Generated by Django 6.0.1 on 2026-01-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0007_alter_hall_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='status',
        ),
        migrations.AddField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
