# Generated by Django 6.0.1 on 2026-01-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0008_remove_hall_status_hall_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_pin', models.CharField(default='2105', help_text='CEO PIN for signature approval', max_length=10)),
                ('principal_pin', models.CharField(default='9011', help_text='Principal PIN for signature approval', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='ceo_status',
            field=models.IntegerField(default=0, help_text='0: Pending, 1: Signed'),
        ),
        migrations.AddField(
            model_name='booking',
            name='principal_status',
            field=models.IntegerField(default=0, help_text='0: Pending, 1: Signed'),
        ),
    ]
