# Generated by Django 6.0.1 on 2026-01-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallapp', '0009_systemsettings_booking_ceo_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ceo_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='principal_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='ceo_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='ceo_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ceo_pin',
            field=models.CharField(blank=True, help_text='CEO approval PIN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='principal_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='principal_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='principal_pin',
            field=models.CharField(blank=True, help_text='Principal approval PIN', max_length=10, null=True),
        ),
    ]
